# Generated by Django 4.2 on 2024-09-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(help_text="密码", max_length=32),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="账号",
                max_length=32,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
